# Generated by Django 4.2 on 2024-04-16 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_platform', '0002_alter_item_image_alter_item_owner_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='item',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reported_by',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
